---
title: "Número Efectivo de Reproducción para las Metropolis en México"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_fragment
bibliography: ref.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=3, fig.height=2)
```


```{r figures, fig.height=2.66, fig.width=4}

 


library(EpiEstim)
library(incidence) #incidence object
library(distcrete) #discretise a pdf
library(epitrix) #from mu, cv to scale and shape in the Gamma distribution
library(latex2exp) #include latex
library(ggplot2) #ggplot


library(matrixStats)
library(readxl)
library(xlsx)
suppressMessages(library(tidyverse)) #str_pad
suppressMessages(library(zip))


#directorios de trabajo
code.dir = 'E:/Documents/informs/research/2020.09.20 Rt Web/code/'
setwd(code.dir)
data.dir = 'E:/Documents/informs/research/2020.09.20 Rt Web/data/'


#directorios con datos o codigo comunes
common.data.dir = 'E:\\Documents\\informs\\research\\covid-common\\data\\'
common.data = 'E:\\Documents\\informs\\research\\covid-common\\'

filename = paste(code.dir, "readData.R", sep = "")
source(filename)


filename = paste(code.dir, "computeRtMetro.R", sep = "")
source(filename)



#filename = paste(common.data.dir, files[length(files)], sep = "")
#covid = readData(filename)



#############
#read the data from the last file of cases

#files in the data.dir directory corresponding to the Health Ministery data
files.pattern = "*COVID19MEXICO.csv"
files <- list.files(path = common.data.dir, pattern =  files.pattern)

filename = paste(common.data.dir, files[length(files)], sep = "")
covid = readData(filename)



#############
#read the list of states

filename = paste(data.dir, "zonas_metropolitanas_2015.csv", sep = "")
zonas.metro.data = read.csv(filename)


#filter in positives
covid.pos = covid[covid$RESULTADO==1,]


#############
#read the list of states

filename = paste(common.data, "estados.csv", sep = "")
estados = read.csv(filename)


#for (state in seq(9 ,9)) { #seq(1,32)) {

# nombre = "MEXICO_PAIS"
# state = 0
# estimate.data = computeRt(state, covid.pos)
#   
#   if (dim(estimate.data)[1] > 0) {
#     filename = paste(data.dir, nombre, ".csv", sep = "")
#     #print(filename)
#     #print(dim(estimate.data))
#     write.csv(estimate.data, filename)
#   }

zonas.metro = unique(zonas.metro.data$CVE_ZM)

files.zip = ""
i = 1
for (zona.metro in zonas.metro) {  
 
#for (state in seq(1 ,32)) { #seq(1,32)) {
#   nombre = estados$ENTIDAD_FEDERATIVA[estados$CLAVE_ENTIDAD == state]
  #extract the metropolitan zone name
  ciudades = zonas.metro.data[zonas.metro.data$CVE_ZM %in% zona.metro,]
  nombre = ciudades[1,"NOM_ZM"] #extract the first name
  cve.zm = ciudades[1,"CVE_ZM"] #extract the first name
  state = ciudades[1,"CVE_ENT"] #extract the first name
  prefix = estados$ABREVIATURA[estados$CLAVE_ENTIDAD == state]
  
  #for the states of Mexico
  #unique.states = sort(unique(covid.pos$ENTIDAD_RES))
  
  #for (state in unique.states) {
  #state = 9 #CDMX
  
  
    
  estimate.data = computeRtMetro(ciudades, zona.metro, covid.pos)
  
  if (dim(estimate.data)[1] > 0) {
    #print(as.character(nombre))
    
    filename = paste(data.dir, prefix,"_",cve.zm, ".csv", sep = "")
    #print(filename)
    #print(dim(estimate.data))
    write.csv(estimate.data, filename)
    files.zip[i] = filename
    i = i + 1
  }
  
}

zipr(zipfile = '../data/metropolis.zip', files = files.zip, include_directories = FALSE)





```

