---
title: "Update Accumulated Positives by Metropolitan Areas"
author: "Joaquín Salas"
date: "September 12, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=3, fig.height=2)
```

## Introducción 

Este programa extrae los datos positivos de los  datos de la Secretaría de Salud para todo el país y los ordena por fecha de inicio de los síntomas.  En caso de que haya registros anteriores, actualiza el archivo *updated_delays.csv*. 



```{r epidemiology}




#directorios de trabajo
code.dir = 'E:/Documents/informs/research/2020.10.14 github nowcasting/code/'
data.dir = 'E:/Documents/informs/research/2020.10.14 github nowcasting/data/'
setwd(code.dir)
common.data.dir = 'E:\\Documents\\informs\\research\\covid-common\\data\\'




filename = paste(code.dir, "updateDelaysMetro.R", sep = "")
source(filename)



#############
#read the list of states

filename = paste(data.dir, "zonas_metropolitanas_2015.csv", sep = "")
zonas.metro.data = read.csv(filename)

#process the whole country
#prefix = "MX"

#print(prefix)
#updateDelays(prefix)

zonas.metro = unique(zonas.metro.data$CVE_ZM)



for (zona.metro in zonas.metro) {
  
  

  
  print(zona.metro)
  updateDelaysMetro(zona.metro, code.dir, data.dir, common.data.dir)
}



```

