---
title: "Update Accumulated Positives"
author: "Joaquín Salas"
date: "September 12, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width=3, fig.height=2)
```

## Introducción 

Este programa extrae los datos positivos de los  datos de la Secretaría de Salud para todo el país y los ordena por fecha de inicio de los síntomas.  En caso de que haya registros anteriores, actualiza el archivo *updated_delays.csv*. 



```{r epidemiology}




#directorios de trabajo
code.dir = 'C:/Users/PC/Documents/informs/research/nowcastingRt/code/'
data.dir = 'C:/Users/PC/Documents/informs/research/nowcastingRt/data/'
setwd(code.dir)

#directorios con datos o codigo comunes
common.data.dir = 'C:\\Users\\PC\\Documents\\informs\\research\\covid-common\\data\\'
 


filename = paste(code.dir, "updateDelays.R", sep = "")
source(filename)



#############
#read the list of states

filename = paste(data.dir, "estados.csv", sep = "")
estados = read.csv(filename)

#process the whole country
prefix = "MX"

print(prefix)
updateDelays(prefix, code.dir, data.dir, common.data.dir)


for (state in seq(1,32)) {
  
   #extract the state name
  prefix = estados$ABREVIATURA[estados$CLAVE_ENTIDAD == state]
  
  print(prefix)
  updateDelays(prefix, code.dir, data.dir, common.data.dir)
}




```

